### ISSUE TITLE
Is this repository a fork or just a mirror?

### ISSUE THREAD

**Issue by madmartin** [vdr-projects/vdr-plugin-rpihddevice#1]
I have noticed some changes in https://github.com/reufer/rpihddevice.
Is this repository a real fork or was the intention to have a mirror?

https://vdr-projects.github.io/ points to https://github.com/reufer/rpihddevice and the maintainer is active.
So maybe its a good idea to send PRs with the changes from here to https://github.com/reufer/rpihddevice, make this repo a mirror again and add a clear repository description.

**Comment by M-Reimer** [comment]
It seemed like @reufer stopped developing his plugin. After contacting him directly via mail I got the information that the plugin is still maintained by him and the latest fixes have been merged by him already. So this repo will go back to an "public archive", again, for the time being.

**Comment by madmartin** [comment]
Thanks for clarification!

**Comment by M-Reimer** [comment]
I've backed up the commits, done by @MarkusEh in a new branch and force-pushed the current upstream state to master. If it ever is required, this repo can be revived at any time.
